branch-defaults:
  aws-dev:
    environment: WebApplication-dev
  development-lb:
    environment: WebApplication-dev
  jr-dev:
    environment: WebApplication-dev
  master:
    environment: relevate
  master-dev:
    environment: MyRelevate
global:
  application_name: WebApplication
  default_ec2_keyname: relevate-eb
  default_platform: Python 2.7
  default_region: us-west-2
  profile: null
  sc: git
