branch-defaults:
  aws-dev:
    environment: WebApplication-dev
  development-lb:
    environment: WebApplication-dev
  master:
    environment: WebApplication-dev
  master-dev:
    environment: MyRelevate-test
global:
  application_name: WebApplication
  default_ec2_keyname: relevate-eb
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
