# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('publishDate', models.DateField()),
                ('updateDate', models.DateField()),
                ('author', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemographicData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('birthday', models.DateField()),
                ('education', models.IntegerField(
                    choices=[(-1, b''), (0, b'Completed high school/GED'), (1, b'Some college no longer attending'),
                             (2, b'Some college currently attending'), (3, b'Graduated with bachelors'),
                             (4, b'Graduated with bachelors'), (5, b'Graduated with PhD'),
                             (6, b'Did not complete high school')])),
                ('employmentStatus', models.CharField(max_length=1,
                                                      choices=[(-1, b''), (b'p', b'part time'), (b'f', b'full time'),
                                                               (b'n', b'not employed'), (b's', b'student')])),
                ('familySize', models.IntegerField()),
                ('gender', models.CharField(max_length=1, choices=[(-1, b''), (b'f', b'female'), (b'm', b'male'),
                                                                   (b't', b'transgender'), (b'q', b'queer')])),
                ('relationshipStatus', models.CharField(max_length=1, choices=[(-1, b''), (b's', b'single'),
                                                                               (b'c', b'casually dating'),
                                                                               (b'r', b'seriously dating'),
                                                                               (b'o', b'committed'), (b'e', b'engaged'),
                                                                               (b'm', b'married'),
                                                                               (b'j', b'just talking')])),
                ('postalCode', models.CharField(max_length=32)),
                ('race', models.CharField(max_length=2)),
                ('salary', models.IntegerField(
                    choices=[(-1, b''), (0, b'Below $10,000'), (1, b'$10,000 - $30,000'), (2, b'$30,000 - $50,000'),
                             (3, b'$50,000 - $80,000'), (4, b'$80,000 - $100,000'), (5, b'$100,000+')])),
                ('sexual_orientation', models.CharField(max_length=1)),
                ('sex', models.CharField(default=-1, max_length=1,
                                         choices=[(-1, b''), (b'f', b'female'), (b'm', b'male'), (b't', b'transgender'),
                                                  (b'q', b'queer')])),
                ('sexualPreference', models.CharField(default=-1, max_length=1,
                                                      choices=[(-1, b''), (b'm', b'men'), (b'b', b'men and women'),
                                                               (b'w', b'women'),
                                                               (b'o', b'otheruser = models.ForeignKey(User)')])),
                ('religion', models.CharField(default=-1, max_length=1,
                                              choices=[(-1, b''), (b'c', b'christianity'), (b'j', b'judaism'),
                                                       (b'i', b'islam'), (b'b', b'buddhism'), (b'h', b'hinduism'),
                                                       (b'a', b'atheism'), (b'g', b'agnostic'), (b'n', b'none'),
                                                       (b'o', b'other')])),
                ('religiousInfluence', models.CharField(default=-1, max_length=1,
                                                        choices=[(-1, b''), (1, b'strongly disagree'), (2, b'disagree'),
                                                                 (3, b'neither agree nor disagree'), (4, b'agree'),
                                                                 (5, b'strongly agree')])),
                ('addictive', models.CharField(default=-1, max_length=1,
                                               choices=[(-1, b''), (b'n', b'never'), (b'r', b'rarely'),
                                                        (b's', b'sometimes'), (b'o', b'often'),
                                                        (b'f', b'frequently')])),
                ('violence', models.CharField(default=-1, max_length=1,
                                              choices=[(-1, b''), (b'n', b'never'), (b'r', b'rarely'),
                                                       (b's', b'sometimes'), (b'o', b'often'), (b'f', b'frequently')])),
                ('breakups', models.CharField(default=-1, max_length=1,
                                              choices=[(-1, b''), (b'n', b'never'), (b'r', b'rarely'),
                                                       (b's', b'sometimes'), (b'o', b'often'), (b'f', b'frequently')])),
                ('verbalEmotionalAbuse', models.CharField(default=-1, max_length=1,
                                                          choices=[(-1, b''), (b'n', b'never'), (b'r', b'rarely'),
                                                                   (b's', b'sometimes'), (b'o', b'often'),
                                                                   (b'f', b'frequently')])),
                ('infidelity', models.CharField(default=-1, max_length=1,
                                                choices=[(-1, b''), (b'n', b'never'), (b'r', b'rarely'),
                                                         (b's', b'sometimes'), (b'o', b'often'),
                                                         (b'f', b'frequently')])),
                ('addictiveOther', models.CharField(default=-1, max_length=1,
                                                    choices=[(-1, b''), (b'n', b'never'), (b'r', b'rarely'),
                                                             (b's', b'sometimes'), (b'o', b'often'),
                                                             (b'f', b'frequently')])),
                ('violenceOther', models.CharField(default=-1, max_length=1,
                                                   choices=[(-1, b''), (b'n', b'never'), (b'r', b'rarely'),
                                                            (b's', b'sometimes'), (b'o', b'often'),
                                                            (b'f', b'frequently')])),
                ('breakupsOther', models.CharField(default=-1, max_length=1,
                                                   choices=[(-1, b''), (b'n', b'never'), (b'r', b'rarely'),
                                                            (b's', b'sometimes'), (b'o', b'often'),
                                                            (b'f', b'frequently')])),
                ('verbalEmotionalAbuseOther', models.CharField(default=-1, max_length=1,
                                                               choices=[(-1, b''), (b'n', b'never'), (b'r', b'rarely'),
                                                                        (b's', b'sometimes'), (b'o', b'often'),
                                                                        (b'f', b'frequently')])),
                ('infidelityOther', models.CharField(default=-1, max_length=1,
                                                     choices=[(-1, b''), (b'n', b'never'), (b'r', b'rarely'),
                                                              (b's', b'sometimes'), (b'o', b'often'),
                                                              (b'f', b'frequently')])),
                ('cyclicRelationships', models.BooleanField(default=-1)),
                ('timesCycled', models.IntegerField(default=-1)),
                ('timesMarried', models.IntegerField(default=-1)),
                ('biologicalChildren', models.IntegerField(default=-1)),
                ('adoptedChildren', models.IntegerField(default=-1)),
                ('stepChildren', models.IntegerField(default=-1)),
                ('lengthOfCurrentRelationship', models.IntegerField(default=-1)),
                ('currentRelationshipHappiness', models.CharField(default=-1, max_length=1,
                                                                  choices=[(-1, b''), (1, b'strongly disagree'),
                                                                           (2, b'disagree'),
                                                                           (3, b'neither agree nor disagree'),
                                                                           (4, b'agree'), (5, b'strongly agree')])),
                ('gettingDivorced', models.NullBooleanField()),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tagName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TagTable',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('article', models.ForeignKey(to='MyRelevate.Article')),
                ('tag', models.ForeignKey(to='MyRelevate.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
